/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using Undo.Server;
namespace Undo.Server
{
  public class TaskManager : Undo.Server.TaskManagerSkeleton
  {
    /// <summary>
    /// Use this constructor to create instances in your code.
    /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
    ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
    /// </summary>
    
    public TaskManager()
    {
      /// TODO: add your code here
    }
    public override Undo.Server.Task onCreateTask(Undo.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"TaskManager.onCreateTask called","Undo.Server.TaskManager");
      /// TODO: add your code here
      return (null);
    }
    public override void onAddTask(Undo.Server.Task task__, Undo.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"TaskManager.onAddTask called","Undo.Server.TaskManager");
      /// TODO: add your code here
    }
    public override void onRemoveTask(int id__, Undo.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"TaskManager.onRemoveTask called","Undo.Server.TaskManager");
      /// TODO: add your code here
    }
  }
  
}
