/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using Lobby.Client;
namespace Lobby.Client
{
  public class Client : Lobby.Client.ClientSkeleton
  {
    /// <summary>
    /// Use this constructor to create instances in your code.
    /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
    ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
    /// </summary>
    
    public Client()
    {
      /// TODO: add your code here
    }

      public override void onJoinedProject(Project project__)
      {
          throw new NotImplementedException();
      }
  }
  
}
