/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using APlayTest.Server;
using APlayTest.Services.Infracstructure;
using sbardos.UndoFramework;

namespace APlayTest.Server
{
    public class APlayServer : APlayTest.Server.APlayServerSkeleton
    {
        private readonly int _port;
        private readonly IProjectManagerFactory _projectManagerFactory;
        private readonly IUndoService _undoService;

        /// <summary>
        /// You should initiate the server here.
        ///  
        /// Note: don't create aplay objects before onCloudReady has been called!
        /// </summary>

        public APlayServer(int port, IProjectManagerFactory projectManagerFactory, IUndoService undoService)
        {
            _port = port;
            _projectManagerFactory = projectManagerFactory;
            _undoService = undoService;
            // Autogenerated log message for call
            APlay.Common.Logging.Logger.LogDesigned(2, "APlayServer constructed", "APlayTest.Server.APlayServer");
            /// TODO: add your code here

            this.InitAsSingle();

        }
        /// <summary>
        /// a client connected
        /// </summary>

        /// <param name="client">
        /// the representation of this client
        /// </param>

        public override void onClientConnect(APlayTest.Server.Client client)
        {
            // Autogenerated log message for call
            APlay.Common.Logging.Logger.LogDesigned(2, "APlayServer.onClientConnect called", "APlayTest.Server.APlayServer");

            client.Id = IdGenerator.GetNextId();

            var projectManager = _projectManagerFactory.CreateProjectManager();

            projectManager.DataClient = client;

            client.ProjectManager = projectManager;

            //Todo: Should move to JoinProject
            //client.UndoManager = new UndoManager(_undoService, client.Id);

           client.TryGetIdEventHandler += ClientOnTryGetIdEventHandler;
            
        }

        private bool ClientOnTryGetIdEventHandler(int desiredId, APlayTest.Server.Client client)
        {
            client.Id = desiredId;
            return true;
        }

        /// <summary>
        /// a client disconnected
        /// </summary>

        /// <param name="client">
        /// the representation of this client
        /// </param>

        public override void onClientDisconnect(APlayTest.Server.Client client)
        {
            // Autogenerated log message for call
            APlay.Common.Logging.Logger.LogDesigned(2, "APlayServer.onClientDisconnect called", "APlayTest.Server.APlayServer");
            /// TODO: add your code here
        }

        public override void onCloudReady()
        {
            base.onCloudReady();

            StartForClients("0.0.0.0:" + _port);
        }
    }

}
