/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using APlayTest.Server;
namespace APlayTest.Server
{
  public class APlayServer : APlayTest.Server.APlayServerSkeleton
  {
    /// <summary>
    /// You should initiate the server here.
    ///  
    /// Note: don't create aplay objects before onCloudReady has been called!
    /// </summary>
    
    public APlayServer()
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"APlayServer constructed","APlayTest.Server.APlayServer");
      /// TODO: add your code here
    }
    /// <summary>
    /// a client connected
    /// </summary>
    
    /// <param name="client">
    /// the representation of this client
    /// </param>
    
    public override void onClientConnect(APlayTest.Server.Client client)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"APlayServer.onClientConnect called","APlayTest.Server.APlayServer");
      /// TODO: add your code here
    }
    /// <summary>
    /// a client disconnected
    /// </summary>
    
    /// <param name="client">
    /// the representation of this client
    /// </param>
    
    public override void onClientDisconnect(APlayTest.Server.Client client)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"APlayServer.onClientDisconnect called","APlayTest.Server.APlayServer");
      /// TODO: add your code here
    }
  }
  
}
