/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using APlayTest.Server;
namespace APlayTest.Server
{
  public class Connection : APlayTest.Server.ConnectionSkeleton
  {
    /// <summary>
    /// Use this constructor to create instances in your code.
    /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
    ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
    /// </summary>
    
    public Connection()
    {
      /// TODO: add your code here
    }
    public override void onSetFromPosition(APlayTest.Server.AplayPoint position__, APlayTest.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Connection.onSetFromPosition called","APlayTest.Server.Connection");
      /// TODO: add your code here
    }
    public override void onSetToPosition(APlayTest.Server.AplayPoint position__, APlayTest.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Connection.onSetToPosition called","APlayTest.Server.Connection");
      /// TODO: add your code here
    }
    public override void onSetTo(APlayTest.Server.Connector connector__, APlayTest.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Connection.onSetTo called","APlayTest.Server.Connection");
      /// TODO: add your code here
    }
    public override void onSetFrom(APlayTest.Server.Connector connector__, APlayTest.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Connection.onSetFrom called","APlayTest.Server.Connection");
      /// TODO: add your code here
    }
    public override void onSetColor(uint Color__, APlayTest.Server.Client client__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Connection.onSetColor called","APlayTest.Server.Connection");
      /// TODO: add your code here
    }
  }
  
}
