/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using APlayTest.Server;
namespace APlayTest.Server
{
  public class Sheet : APlayTest.Server.SheetSkeleton
  {
    /// <summary>
    /// Use this constructor to create instances in your code.
    /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
    ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
    /// </summary>
    
    public Sheet()
    {
      /// TODO: add your code here
    }
    public override APlayTest.Server.BlockSymbol onCreateBlockSymbol()
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Sheet.onCreateBlockSymbol called","APlayTest.Server.Sheet");
      /// TODO: add your code here
      return (null);
    }
    public override void onAdd(APlayTest.Server.BlockSymbol blockSymbol__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Sheet.onAdd called","APlayTest.Server.Sheet");
      /// TODO: add your code here
    }
  }
  
}
