/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using APlayTest.Client;
namespace APlayTest.Client
{
  public class Project : APlayTest.Client.ProjectSkeleton
  {
    /// <summary>
    /// Use this constructor to create instances in your code.
    /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
    ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
    /// </summary>
    
    public Project()
    {
      /// TODO: add your code here
    }
    public override APlayTest.Client.Sheet onCreateSheet(String name__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Project.onCreateSheet called","APlayTest.Client.Project");
      /// TODO: add your code here
      return (null);
    }
    public override APlayTest.Client.SheetList onGetSheets()
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Project.onGetSheets called","APlayTest.Client.Project");
      /// TODO: add your code here
      return (new APlayTest.Client.SheetList());
    }
    public override void onSetName(String name__)
    {
      // Autogenerated log message for call
      APlay.Common.Logging.Logger.LogDesigned(2,"Project.onSetName called","APlayTest.Client.Project");
      /// TODO: add your code here
    }
  }
  
}
