/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using Undo.Server;
namespace Undo.Server
{
    public class Task : Undo.Server.TaskSkeleton
    {
        /// <summary>
        /// Use this constructor to create instances in your code.
        /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
        ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
        /// </summary>
        /// <param name="description"></param>
        public Task()
        {

        }


        public Task(string description)
            : base()
        {

            Description = description;
        }
        public override void onSetDone(bool done__, Undo.Server.Client client__)
        {
            // Autogenerated log message for call
            APlay.Common.Logging.Logger.LogDesigned(2, "Task.onSetDone called", "Undo.Server.Task");
            IsDone = done__;
        }
        public override void onSetTaskDescription(String description__)
        {
            // Autogenerated log message for call
            APlay.Common.Logging.Logger.LogDesigned(2, "Task.onSetTaskDescription called", "Undo.Server.Task");
            Description = description__;
        }
    }

}
