/**
* automatically generated by APlay 2.0.2.1
* www.aplaypowered.com
*/

using System;
using System.Collections.Generic;
using APlay.Common;
using APlay.Common.Utils;
using APlay.Common.DataTypes;
using Lobby.Server;
namespace Lobby.Server
{
  public class Client : Lobby.Server.ClientSkeleton
  {
    /// <summary>
    /// Use this constructor to create instances in your code.
    /// Note: leave the APInitOb null. Aplay sets this object if initialized by aplay.
    ///  if you want to determine in the constructor if the object is user created or by aplay - check IsInitializedByAPlay
    /// </summary>
    
    public Client()
    {
      /// TODO: add your code here
    }

      public override void onJoinProject(Client sender__, int projectId__)
      {
          throw new NotImplementedException();
      }

      public override void onCreateProject(Client sender__, string name__)
      {
          throw new NotImplementedException();
      }

      public override void onSearchProjects(string searchString__)
      {
          throw new NotImplementedException();
      }

      public override void onSelectProject(int projectId__)
      {
          throw new NotImplementedException();
      }
  }
  
}
